{{- /*

common.secret is a generic key/value secret.

It takes two objects:
  - .top
  - .secret

It will check .secret for the following:
  - .secret.items: a map of key/value pairs.
  - .secret.files: a map of key/filename pairs. This will lookup filename in .Files
    and place the contents into the secret.

*/ -}}
    {{define "common.secret" -}}{{- $top := .top -}}
apiVersion: v1
kind: Secret
type: Opaque
{{ template "common.metadata" (dict "top" .top "metadata" .secret) }}
data:
  {{- range $key, $val := .secret.items }}
  {{$key | quote }}: |-
{{ $val | b64enc | wrap 80 | indent 4 }}
{{- end -}}
  {{- range $key, $fname := .secret.files}}
  {{$key | quote }}: |-
{{ $top.Files.Get $fname | b64enc | wrap 80 | indent 4 }}
{{- end -}}
{{- end}}
